# GitHub Sponsors Configuration

github: BoozeLee
patreon: # Add if available
open_collective: # Add if available
ko_fi: # Add if available
tidelift: # Add if available
community_bridge: # Add if available
liberapay: # Add if available
issuehunt: # Add if available
otee: # Add if available
custom: ['https://bakerstreetproject221b.store/sponsor']

